services:
  app:
    container_name: utang-inamo
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - '8100:8100'
      - '35729:35729'
      - '53703:53703'
    command: ionic serve --external